# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu:
# - {name: 'Interesting Facts',  url: 'facts'}
# - {name: 'Learning Resources', url: 'resources'}
# - {name: 'Sample Posts',       url: 'sample-posts'}
- {name: 'Blog' , url: 'blog'}
- {name: 'About', url: 'about'}
- {name: 'CV'   , url: 'cv'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github',   link: 'https://github.com/dalan-loudermilk'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/dalanloudermilk/'}
- {icon: 'envelope', link: 'mailto:dalan-AT-umd.edu'}
- {icon: 'google',   link: 'https://scholar.google.com/citations?user=w_I1ajgAAAAJ'}
- {icon: 'youtube',  link: 'https://www.youtube.com/@DalanLoudermilk'}
# - {icon: 'rss-square', link: 'feed.xml'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Share'

related_posts: 'Related: '

post_date_prefix: 'Posted on'
